server {
    listen 80;
    
    root /usr/share/nginx/html;
    index index.html;
    
    # Regra genérica para qualquer slug
    location ~ ^/([^.]+)$ {
        try_files /$1.html =404;
    }
    
    # Configuração para arquivos estáticos e diretórios
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Imagens no cache de longo prazo.
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|webp|avif|ico|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    
    # Configuração para páginas HTML específicas
    location ~ \.html$ {
        try_files $uri =404;
    }
}